README.md, snapyr/src/main/java/com/snapyr/sdk/ConnectionFactory.java, snapyr/src/main/java/com/snapyr/sdk/Snapyr.java, snapyr/src/main/java/com/snapyr/sdk/integrations/Logger.java, snapyr/src/test/java/com/snapyr/sdk/LoggerTest.kt
Enable Snapyr integration by default, as it is not part of the configs returned by the API.
Fix endpoint and a couple remnants from "Snapyr" rename
=> Integration fixes

snapyr/src/main/java/com/snapyr/sdk/SnapyrIntegration.java, snapyr/src/main/java/com/snapyr/sdk/notifications/SnapyrNotificationHandler.java
Deep link url wasn't being set correctly on the notification after switching to lifecycle callbacks, so it was being dropped. This fixes that
=> Deeplink fix

snapyr/src/main/java/com/snapyr/sdk/internal/PushTemplate.java, snapyr/src/main/java/com/snapyr/sdk/notifications/SnapyrNotificationHandler.java
Fixes to make SDK work more reliably without consuming app needing to change build settings or SDK target versions. (more than already required for our integration, at least)
Using lambdas means the consuming app needs to set their build settings to be compatible with Java 8. Taking them out so our SDK can be used without requiring changes on the consumer's side here.
TODO: see if we can use Java 8 stuff and desugar during our own build process?
The push payload sometimes (or maybe always?) includes `"imageUrl": ""`, i.e. empty string instead of null/undefined. Use `isNullOrEmpty` to skip more reliably, so there aren't errors being logged for no reason
So that consuming app doesn't get yelled at when using a min SDK target of 31 or higher, which enforces that FLAG_IMMUTABLE or …
=> Bug fixes from client feedback

snapyr/src/main/java/com/snapyr/sdk/notifications/SnapyrFirebaseMessagingService.java, snapyr/src/main/java/com/snapyr/sdk/notifications/SnapyrNotificationHandler.java
Fixes action button deeplinks (https://snapyr.atlassian.net/browse/UNIC-141) and a couple minor things along the way.
[Fix for action button deeplinks all using the last button's value](https://github.com/snapyrautomation/snapyr-android-sdk/commit/d3dd68833a1a872ff04c87988d3691894c3f2061) 
The first parameter to TaskBuilder getPendingIntent is `requestCode`. Although this doesn't seem to be documented ANYWHERE, reusing the same request code causes future buttons to override the intent on previous buttons that used the same request code, causing every action button on a push notification to share the deeplink value of the last-registered button.
[Build fix - FLAG_IMMUTABLE only available on M or later](https://github.com/snapyrautomation/snapyr-android-sdk/commit/e054e4f7697d535d41132bd70ba …
=> Action button deeplink fix

snapyr/src/main/java/com/snapyr/sdk/notifications/SnapyrNotificationHandler.java
(in addition to action button PendingIntents, where it was already set)
Fixes crash in newer versions of Android (31 (S) or newer), where FLAG_IMMUTABLE or FLAG_MUTABLE is required
=> Add FLAG_IMMUTABLE to main notification PendingIntent

snapyr/src/main/java/com/snapyr/sdk/Snapyr.java, snapyr/src/main/java/com/snapyr/sdk/notifications/SnapyrNotificationHandler.java
Fix error "Method removeObserver must be called on the main thread" when shutting down, at least on newer Android versions.
=> Fix error "Method removeObserver must be called on the main thread"

snapyr/src/main/java/com/snapyr/sdk/notifications/SnapyrNotificationListener.java
Attempting to close notification drawer crashes due to permission error on later Android versions, which prevents notification impression/behavior tracks from being saved. Notification drawer dismissal seems to happen automatically anyway (see comments in TrackerUtil.java) so simply removing this to fix this issue.
=> Fix exception on notification listener

snapyr/src/main/java/com/snapyr/sdk/Snapyr.java, snapyr/src/main/java/com/snapyr/sdk/http/ConnectionFactory.java, snapyr/src/main/java/com/snapyr/sdk/inapp/InAppManager.java, snapyr/src/main/java/com/snapyr/sdk/inapp/requests/AckUserActionRequest.java, snapyr/src/main/java/com/snapyr/sdk/inapp/requests/GetUserActionsRequest.java, snapyr/src/main/java/com/snapyr/sdk/internal/Utils.java, snapyr/src/test/java/com/snapyr/sdk/SnapyrTest.kt
Fixes several bugs surfaced during in-app integration testing.
* Fix crash if Snapyr init'd outside of UI thread with an in-app config defined.
In-app manager starts up a poller - this was defaulting to a handler that expected to init from within the UI thread.
Moves to a thread pool that uses the same mechanism as the main batch queue handling code.
* Connection fixes for ack/queued action poll 
Needed to swap around some of the setDoInput/setDoOutput flags to correctly configure requests. They are named confusingly
* Activity tracking fix for post-main-activity init
Fixes bug in Snappy Bird test app - it initializes Snapyr after the main activity has started. This is similar to React Native logic and ensures the first/main activity is tracked by Snapyr in this case
=> In app fixes

snapyr/src/main/java/com/snapyr/sdk/Snapyr.java, snapyr/src/main/java/com/snapyr/sdk/inapp/webview/WebviewModalView.java
Moves in-app tracking to shared, public Snapyr functions so users can manually track custom in-app messages. This facilitates the same for React Native SDK.
(https://snapyr.atlassian.net/browse/MEKA-458)
=> Move in-app tracking to shared Snapyr functions

snapyr/src/main/java/com/snapyr/sdk/inapp/InAppActionType.java, snapyr/src/main/java/com/snapyr/sdk/inapp/InAppContentType.java, snapyr/src/main/java/com/snapyr/sdk/inapp/InAppMessage.java
Makes `InAppContentType`/`InAppActionType` public so consumers can use them to check incoming messages.
=> Inapp public enums

snapyr/src/main/java/com/snapyr/sdk/inapp/InAppContent.java
All SDKs are now passing this as a parsed map rather than a raw JSON string; this serializes fine and avoids needing to check and re-parse after receiving e.g. on the React Native side
=> InAppContent.asValueMap - use map for JSON payload

snapyr/src/main/java/com/snapyr/sdk/inapp/InAppActionProcessor.java, snapyr/src/main/java/com/snapyr/sdk/inapp/InAppManager.java, snapyr/src/test/java/com/snapyr/sdk/inapp/InAppTest.kt
Send/confirm ack requests before triggering user callbacks; don't let user callback code affect processing. ack-then-callback is in line with other SDKs. Also moves calls to user-defined callbacks into their own thread, which prevents timing issues or exceptions from user code from interrupting our processing.
Also has some sync/timing improvements on the poller to prevent some problems I noticed with polling requests accumulating and rapid-firing when pausing in the step debugger (similar situations could possibly happen without the debugger; more details in commit message).
=> In-app ack fixes

snapyr/src/main/java/com/snapyr/sdk/Snapyr.java, snapyr/src/main/java/com/snapyr/sdk/inapp/InAppActionProcessor.java, snapyr/src/main/java/com/snapyr/sdk/inapp/InAppContent.java, snapyr/src/main/java/com/snapyr/sdk/inapp/InAppMessage.java, snapyr/src/main/java/com/snapyr/sdk/inapp/InAppPayloadType.java, snapyr/src/test/java/com/snapyr/sdk/inapp/InAppTest.kt
* Small consistency tweaks after going through documentation updates for several SDKs
Updates naming to be consistent with other SDKs and other parts of the system - InAppContent has a `payload` and `payloadType` rather than `content` and `contentType`.
* Correct nullability on tracking method params 
* Fix params that were NOT nullable, but marked as nullable, to be correct.
* Also adds overload method for `trackInAppMessageClick` so that additional properties are optional, for user convenience and consistency with other SDKs.
=> In-app messaging - tweaks from documentation updates

RELEASING.md, build.gradle, gradle/mvn-publish.gradle, snapyr/build.gradle, snapyr/src/main/java/com/snapyr/sdk/http/BatchUploadQueue.java, snapyr/src/main/java/com/snapyr/sdk/http/BatchUploadRequest.java
* Fix Javadoc errors on gradle publish 
* Add generated BuildConfig to classpath - fixes javadoc errors like `error: cannot find symbol import  com.snapyr.sdk.core.BuildConfig;`
* Remove `<` character in javadoc comments that the plugin complains about
* Remove unused/sunsetted bintray and jcenter
Both of these were sunsetted in 2021. Including these repositories in our gradle files appears to have had no ill effect, but they didn't do anything, so cleaning up.
* Update release instructions to include tagging
=> Gradle publish fixes

snapyr/src/main/java/com/snapyr/sdk/Snapyr.java
Track/identify/etc. calls add events to the queue on executor, but flush was calling sendQueue.flush directly/immediately. That could result in sendQueue.flush being run before the event reached the queue, causing the flush to miss that event.
This moves the sendQueue.flush call to the executor as well, so it will run sequentially after any previously-called event queuing methods.
Fixes push tracking events not making it to back end when a notification was tapped after the application was closed
=> Notification - immediate flush fix

build.gradle, gradle/android.gradle, gradle/mvn-publish.gradle, snapyr/build.gradle, snapyr/src/main/java/com/snapyr/sdk/Snapyr.java, snapyr/src/main/java/com/snapyr/sdk/http/BatchUploadQueue.java, snapyr/src/main/java/com/snapyr/sdk/internal/TrackerUtil.java, snapyr/src/main/java/com/snapyr/sdk/notifications/SnapyrFirebaseMessagingService.java, snapyr/src/main/java/com/snapyr/sdk/notifications/SnapyrNotification.java, snapyr/src/main/java/com/snapyr/sdk/notifications/SnapyrNotificationHandler.java, snapyr/src/main/java/com/snapyr/sdk/notifications/SnapyrNotificationListener.java, snapyr/src/test/java/com/snapyr/sdk/notifications/SnapyrNotificationTest.kt
Adds event broadcasts when Snapyr push notifications are received or tapped. A consumer can set up a broadcast receiver to listen to these and run custom code when a push notification event occurs. This enables callbacks in the React Native SDK, but could also be listened to directly by other Android code.
A lot of the code changes in this PR involve moving logic from `SnapyrNotificationListener` and `SnapyrFirebaseMessagingService` into a new class, `SnapyrNotification`. This is a structured representation of a notification object. It implements the Parcelable interface so that it can be passed around as part of an Intent, and reconstituted back to a full `SnapyrNotification` object on the receiving side.
Updates the Gradle config to allow this project to be included as a local …
=> Push notification event broadcast

gradle/android.gradle, snapyr/build.gradle
* Adds explicit dependency from subdirectory Gradle files to the root Gradle file when included as a subproject. This makes it easier to include this repo in another project for local dev/testing (requires less boilerplate in the consuming project)
* Adds a `BUILD_DATE` field with the current timestamp upon build, so we can include this for informational purposes in testing apps
=> Local dev improvements

snapyr/src/main/java/com/snapyr/sdk/notifications/SnapyrNotificationHandler.java
Some Android devices/OSes, including Google Pixel, automatically make long text notifications expandable, but others do not. In that case notifications with text that exceeds the width of the notification will have the text truncated with an ellipsis, with no way to expand the notification to see more.
Setting `BigTextStyle` ensures that notifications with longer text can be expanded.
This applies only to notifications that do not include an image. Notifs w/ image will override this with a `BigPictureStyle` which includes the image, and a length-limited summary text. Note that BigPictureStyle does NOT allow the text to be expanded, so notifs with images can only display the ellipsis-truncated text alongside the image.
=> Fix - text-only notifs expandable on some OSes

snapyr/src/main/java/com/snapyr/sdk/Snapyr.java, snapyr/src/main/java/com/snapyr/sdk/inapp/webview/WebviewModalView.java, snapyr/src/main/java/com/snapyr/sdk/internal/PushTemplate.java, snapyr/src/main/java/com/snapyr/sdk/notifications/SnapyrFirebaseMessagingService.java, snapyr/src/main/java/com/snapyr/sdk/notifications/SnapyrNotificationHandler.java
* Remove @RequiresApi; use util date parser 
Minor update to use the existing date parser utility method in PushTemplate instead of newer Java utils, allowing removal of @RequiresApi decorators that prevent notifications from working on older Android versions
* Add settings to make notifications show heads-up preview on Android N + older
* Use plain WebViewClient (no override for now) 
InAppWebviewClient `shouldOverrideUrlLoading` is currently unused, as the overlay script cancels clicks on <a> tags and sends event data to the SDK instead for handling.
Existing code in InAppWebviewClient could cause error/crash if the overlay script doesn't work for some reason, so disabling it to be safe. We may want to update this and use again in the future, so leaving the class here
=> Android N fixes

snapyr/src/main/java/com/snapyr/sdk/Snapyr.java, snapyr/src/main/java/com/snapyr/sdk/notifications/SnapyrFirebaseMessagingService.java
Moves the logic from messaging service `onMessageReceived` to another method, and wraps the entire call in a try/catch to ensure that any unexpected exceptions do not result in a crash.
Also includes a couple of more specific safety improvements.
=> Notification safety
